services:
  globetrotter-service:
    restart: always
    image: globetrotter-service:1.0
    environment:
      PRIMARY_EMAIL: kumarvishnu1619@gmail.com
      PRIMARY_EMAIL_PASSWORD: zunwczuiiqequwmt
      JWT_SECRET: UHJvZ3JhbW1lcnMgZG9uJ3QgZGllOyB0aGV5IGp1c3QgZ28gb2ZmbGluZS4=
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: password
      MYSQL_HOST: globetrotter-mysql
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      - globetrotter-mysql
    ports:
      - "9999:9999"
    networks:
      - globetrotter-network

  globetrotter-mysql:
    restart: always
    image: mysql:9.1.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql/sql:/docker-entrypoint-initdb.d/
    networks:
      - globetrotter-network

networks:
  globetrotter-network:
    driver: bridge
volumes:
  mysql_data: